### ISSUE TITLE
Validation Form in Contact Page

### ISSUE THREAD

**Issue by acatzk** [VeoScript/veoport#55]
I suggest to experiment using `react-hook-form` it may feels intimidating at first but you get to used to it when you eventually applied it in every forms submission...

![image](https://user-images.githubusercontent.com/38458781/114897047-75b92f00-9e43-11eb-947d-245ff81e1413.png)

**Comment by VeoScript** [comment]
yes, actually I already installed that. but I have a problem in nodemailer in production as of now. Anyway i will fix that asap.
