### ISSUE TITLE
Change NProgress Color

### ISSUE THREAD

**Issue by acatzk** [VeoScript/veoport#61]
### **You can change it here with hexa color you like**

![indicator](https://user-images.githubusercontent.com/38458781/114972077-55738980-9eb0-11eb-81b3-53189846b28e.png)

**Comment by VeoScript** [comment]
i have already changed the NProgress color
![image](https://user-images.githubusercontent.com/26340308/114972518-388b8600-9eb1-11eb-888c-9782fcadc0fb.png)
